name: Compile LaTeX

on:
  push:
    branches: [ "main" ]  # Запускать при пуше в ветку main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jakoblassmann/latex:latest  # Образ с LaTeX
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile LaTeX to PDF
        run: |
          pdflatex -interaction=nonstopmode main.tex
          pdflatex -interaction=nonstopmode main.tex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: lectures
          path: lectures.pdf
